- name: Install New Relic Infrastructure
  hosts: zookeeper:kafkabrokers
  roles: 
    - name: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: "{{ NRIA_LICENSE_KEY }}"
          enable_process_metrics: true
          include_matching_metrics:
            - "java*"