- name: Install Zookeeper
  hosts: zookeeper

  roles:
    - name: sansible.zookeeper

- name: Install Kafka Server
  hosts: kafkabrokers

  roles:
    - name: sansible.kafka
      sansible_kafka_zookeeper_hosts:
        - newrelic-kafka-tutorial-zookeeper
      sansible_kafka_server_properties_defaults:
        broker.id: {{ broker_id }}