- name: Install Zookeeper
  hosts: zookeeper

  pre_tasks:
    - name: update apt
      apt:
       update_cache: yes

  roles:
    - name: sansible.zookeeper

- name: Install Kafka Server
  hosts: kafkabrokers

  roles:
    - name: sansible.kafka
      sansible_kafka_zookeeper_hosts:
        - newrelic-kafka-tutorial-zookeeper:2181
      sansible_kafka_server_properties:
        broker.id: "{{ broker_id }}"
        advertised.listeners: "PLAINTEXT://{{dns_name}}:{{ sansible_kafka_port }}"
