#!/bin/sh
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

set -e
set -x

systemctl status newrelic-infra

if [ ! -f /etc/newrelic-infra/integrations.d/kafka-config.yml ]; then
    exit 1;
fi

exit 0
