apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-integration-cfg # aimed to be safely overridden by users
  namespace: default
data:
  nri-flex.yml: |
    integrations:
      - name: nri-flex
        config:
          name: my-k8s-flex
          apis:
            - event_type: k8sApiResponseTime
              run: echo "{\"apiResponseTime.ms\":$(curl "http://localhost:8080/api/v1/nodes" -s -o /dev/null -w "%{time_starttransfer}\n")}"
