#!/bin/bash
#
# This is a sample setup script. Rename this file to setup-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you setup the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

set -e 

echo "Installing Ansible"
sudo apt update
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible

sed -i 's/^#host_key_checking.*$/host_key_checking = False/' /etc/ansible/ansible.cfg

ansible-galaxy install newrelic.newrelic-infra
ansible-galaxy install sansible.kafka
