#!/bin/bash

# Reset home dir
cd /root/

# Download the first New Relic config
mkdir new-relic/
pushd new-relic/
wget https://raw.githubusercontent.com/polfliet/instruqt/master/nr-flex/assets/nri-k8s.yml
popd

# Set workdir
set-workdir $(pwd)/new-relic
