#!/bin/sh

set -x

echo "Installing Docker"
apt-get remove -y docker docker-engine docker.io containerd runc
apt-get update
apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io

echo "Installing Docker Compose"
curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
curl -L https://raw.githubusercontent.com/docker/compose/1.27.4/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose

echo "Installing New Relic Infrastructure"
curl -s https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | apt-key add -
printf "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt bionic main" | tee -a /etc/apt/sources.list.d/newrelic-infra.list
apt-get update
apt-get install newrelic-infra -y

echo "Downloading assets"
curl -L "https://github.com/polfliet/instruqt/raw/master/consolidating-your-data-with-new-relics-telemetry-data-platform/dist/assets.tar.gz" -o /var/tmp/assets.tar.gz
tar -C /var/tmp -xf /var/tmp/assets.tar.gz
cp -r /var/tmp/assets/apps ~

cd ~/apps

cat << EOF > .env
#Delete or comment this line to enable the agent
NEW_RELIC_ENABLED=false

# Uncomment the line below and insert your licesne key
#NEW_RELIC_LICENSE_KEY=<YOUR LICENSE KEY HERE>

#####################################################
# You shouldn't need to edit anything below this line
ECOMMERCE_API_HOST_LOG_DIR=/var/log/ecommerce-api.log
EOF

docker-compose up -d --build

exit 0
