apiVersion: apps/v1
kind: Deployment
metadata:
  name: serializer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: serializer
  template:
    metadata:
      labels:
        app: guestbook
        tier: serializer
    spec:
      containers:
      - name: frontend
        image: ghcr.io/kidk/kubernetes-demo-apps-serializer:latest       