#!/bin/bash

# Download the first New Relic config
mkdir new-relic/
pushd new-relic/
wget https://raw.githubusercontent.com/polfliet/instruqt/master/kubernetes-new-relic-university/assets/newrelic/nri-k8s.yaml
popd

# Set workdir
set-workdir $(pwd)/new-relic
