version: "3.8"
services:

  ecommerceapi:
    build: ./ecommerce-api
    ports:
      - "3000:3000"
    environment:
      - NEW_RELIC_LICENSE_KEY
      - LOG_FILE=TRUE
    volumes:
        - ${ECOMMERCE_API_HOST_LOG_DIR}:/home/node/app/logs

  loadgen:
    build: ./loadgen
    depends_on:
      - proxy
  
  proxy:
    build: ./proxy
    depends_on:
      - ecommerceapi
    ports:
      - "80:80"