#!/bin/bash

kubectl describe configmap | grep nri-flex
if [ $? -ne 0 ]; then
    fail-message "Could not find Flex integration. Please follow the steps and uncomment the Flex integration. Don't forget to apply the changes."
fi
