#!/bin/sh
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

set -e
echo "This is the check script"

test -f /etc/newrelic-infra/integrations.d/daily-total-flex.yml

exit 0
