#!/bin/bash

# Reset home dir
cd /root/

# Wait for kubernetes to become available
if ! curl --silent --fail --output /dev/null http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/; then
  echo "Starting Kubernetes, this may take a minute or so"
  while ! curl --silent --fail --output /dev/null http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/; do printf "." && sleep 1; done || break
  printf "done."
  echo ""
fi

# Download a bad pod with wrong image to generate events
pushd app/
wget https://raw.githubusercontent.com/polfliet/instruqt/master/kubernetes-new-relic-university/assets/app/unknown.yaml
kubectl apply -f unknown.yaml -n demo-app
popd

# Download the New Relic event config
pushd new-relic/
wget https://raw.githubusercontent.com/polfliet/instruqt/master/kubernetes-new-relic-university/assets/newrelic/nri-k8s-events.yaml
popd

# Set workdir
set-workdir $(pwd)/new-relic
