apiVersion: v1
kind: Service
metadata:
  name: parser
  labels:
    app: guestbook
    tier: parser
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: guestbook
    tier: parser
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parser
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: parser
    spec:
      containers:
      - name: parser
        image: docker.io/spolfliet/newrelic-k8s-guestbook-parser:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secret
              key: new_relic_license_key
        - name: NEW_RELIC_APP_NAME
          value: K8s guestbook - parser
          # tells the node.js app to pause at random intervals
        - name: LOOK_BUSY
          value: f
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
          - containerPort: 3000
